# Generated by Django 5.0.2 on 2024-03-17 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('description', models.TextField(verbose_name='Description')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars', verbose_name='Avatar')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to='accounts.partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Establishment',
                'verbose_name_plural': 'Establishments',
            },
        ),
    ]
